---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: lkNum

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: 2

conditions:
  - allOf:
      - property:
          name: rox.screen_width
          operator: eq
          operands:
            - 123
    flagValue:
      valueWrittenInCode: true
