---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: booleanFlagRomain

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 0
    from: 2026-03-10T14:17:00Z
  - percentage: 100
    from: 2026-03-10T14:22:00Z

conditions: []
