---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: titleSizeRomain

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 20
    option: 12
  - percentage: 20
    option: 1e+33
  - percentage: 20
    option: 14
  - percentage: 20
    option: 18
  - percentage: 20
    option: 24

conditions: []
