---
apiVersion: v1
kind: flag-configuration

flag: enableTutorialSuborg

enabled: false

defaultValue: valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.app_release
          operator: regex
          operands:
              - "1234"
    flagValue: false
