---
apiVersion: v1
kind: flag-configuration

flag: numberFlag

enabled: false

defaultValue: 1

conditions:
  - allOf:
      - property:
          name: rox.app_release
          operator: in-array
          operands:
              - "1"
    flagValue: 2
