---
apiVersion: v1
kind: flag-configuration

flag: titleColorsSuborg

enabled: false

defaultValue: valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.app_release
          operator: regex
          operands:
              - "11234"
    flagValue:
      valueWrittenInCode: true
