---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: asdasda

description: 

conditions:
  allOf:
    - property:
        name: rox.screen_height
        operator: eq
        operands:
            - 123123
