---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: asdasdsd

description: 

conditions:
  anyOf:
    - property:
        name: rox.screen_width
        operator: eq
        operands:
            - 123123
