---
apiVersion: v1
kind: target-group

name: BegotestAudit

description: just for fun

conditions:
  allOf:
    - property:
        name: rox.app_release
        operator: regex
        operands:
            - "1234"
