---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: BegotestAudit

description: just for fun

conditions:
  allOf:
    - property:
        name: rox.app_release
        operator: regex
        operands:
            - "1234"
    - property:
        name: rox.now2
        operator: after
        operands:
            - "2024-11-12T23:00:00.000Z"
