---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: gregTG

description: 

conditions:
  allOf:
    - property:
        name: number-prop
        operator: gte
        operands:
            - 245.2
    - property:
        name: string-prop
        operator: in-array
        operands:
            - asdf
