---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: gregAssistantTG

description: made by AI

conditions:
  allOf:
    - property:
        name: testgreg
        operator: is-false
