---
apiVersion: v1
kind: target-group

name: logged-in-or-beta-user-on-phone

description: Phone users who are either logged in, or beta users.

conditions:
  anyOf:
    - anyOf:
        - group:
            name: targetPhoneUse
    - property:
        name: isLoggedIn
        operator: is-true
