---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: suborg

description: changing description

conditions:
  allOf:
    - property:
        name: rox.app_release
        operator: regex
        operands:
            - "1234"
    - property:
        name: rox.distinct_id
        operator: regex
        operands:
            - abcde
    - anyOf:
        - group:
            id: e1225aae-1c9b-41f5-4bc0-829d8e3b73cb
