---
apiVersion: v1
kind: target-group

name: targetPhoneUse

description: 

conditions:
  allOf:
    - anyOf:
        - group:
            name: BetaUsers
        - group:
            name: BetaUsers
        - group:
            name: BetaUsers
