---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: te

description: 

conditions:
  allOf:
    - property:
        name: rox.now
        operator: before
        operands:
            - "2025-04-07T22:00:00.000Z"
