---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: test-tg-blabla

description: 

conditions:
  allOf:
    - property:
        name: rox.screen_width
        operator: eq
        operands:
            - 123
