---
apiVersion: v1
kind: target-group

name: test-delete

description: 

conditions:
  allOf:
    - property:
        name: rox.app_release
        operator: in-array
        operands:
            - "1"
