---
apiVersion: v1
kind: target-group

name: test TG

description: asdasd

conditions:
  allOf:
    - property:
        name: rox.app_release
        operator: regex
        operands:
            - "2123"
