---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: test-delete

description: 

conditions:
  anyOf:
    - property:
        name: rox.app_release
        operator: regex
        operands:
            - "123"
    - property:
        name: rox.app_release
        operator: is-undefined
