---
apiVersion: v1
kind: target-group

name: test2

description: test

conditions:
  allOf:
    - property:
        name: rox.app_release
        operator: in-array
        operands:
            - "1234"
