---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: tg-referenced

description: 

conditions:
  allOf:
    - property:
        name: rox.app_release
        operator: regex
        operands:
            - "123"
