---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: tg-referencing

description: 

conditions:
  allOf:
    - property:
        name: test-cp
        operator: is-true
    - anyOf:
        - group:
            id: 8bd054d0-5b60-44a4-aa35-95e3f6bb3d5c
