---
apiVersion: v1
kind: target-group

name: tg2

description: add some description

conditions:
  allOf:
    - property:
        name: rox.app_release
        operator: regex
        operands:
            - "1234"
