---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: tst-update

description: asdasd

conditions:
  allOf:
    - property:
        name: rox.app_release
        operator: regex
        operands:
            - "23"
