---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: booleanFlagRomain

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 60
    option: true
  - percentage: 40
    option: false

conditions: []
