---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: booleanFlagRomain

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 50
    option: true
  - percentage: 50
    option: false

conditions:
  - allOf:
      - property:
          name: rox.screen_width
          operator: eq
          operands:
            - 123
    flagValue:
      - percentage: 50
        option: true
      - percentage: 50
        option: false
