---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: booleanFlagRomain

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.now
          operator: in-between
          operands:
            - "2025-03-17T23:00:00.000Z"
            - "2025-03-18T23:00:00.000Z"
    flagValue: false
