---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: booleanFlagRomain

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - property:
          name: string prop
          operator: in-array
          operands:
            - ' 2'
            - ' 4'
            - ' 6'
    flagValue: false
  - allOf:
      - anyOf:
          - group:
              name: test-delete
    flagValue: false
