---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: booleanFlagRomain

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: true

conditions:
  - allOf:
      - property:
          name: newcp
          operator: is-true
    flagValue: false
  - allOf:
      - property:
          name: rox.screen_width
          operator: ne
          operands:
            - 2
    flagValue: false
  - allOf:
      - property:
          name: rox.screen_width
          operator: eq
          operands:
            - 1
    flagValue: false
