---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: corinne

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - anyOf:
          - group:
              name: suborg
      - property:
          name: test prop
          operator: is-true
    flagValue:
      valueWrittenInCode: true
