---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: fontColor

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.distinct_id
          operator: regex
          operands:
            - "12345"
    flagValue:
      valueWrittenInCode: true
  - allOf:
      - property:
          name: rox.app_release
          operator: regex
          operands:
            - "123"
    flagValue:
      valueWrittenInCode: true
