---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: lkBool

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: true

conditions:
  - allOf:
      - flag:
          name: asd
          value: "true"
    flagValue: false
  - allOf:
      - property:
          name: rox.app_release
          operator: semver-eq
          operands:
            - "2"
    flagValue: false
