---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: lkBool

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - property:
          name: rox.screen_width
          operator: eq
          operands:
            - 12222
    flagValue: false
