---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: lkBool

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: true

conditions:
  - allOf:
      - property:
          name: rox.platform
          operator: regex
          operands:
            - "89"
    flagValue: false
