---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: lkBool

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 1
    from: 2025-03-19T13:06:00Z
  - percentage: 100
    from: 2025-03-20T13:11:00Z

conditions:
  - allOf:
      - property:
          name: rox.platform
          operator: regex
          operands:
            - "89"
    flagValue: false
