---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: lkBool

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - flag:
          name: asd
          value: "true"
    flagValue: false
  - allOf:
      - property:
          name: rox.screen_width
          operator: eq
          operands:
            - qwe
    flagValue: false
