---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: lkBool

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: true

conditions:
  - anyOf:
      - property:
          name: rox.screen_width
          operator: eq
          operands:
            - qwe
      - anyOf:
          - group:
              id: fc0a12f8-ab3b-4dec-b1bd-7b7ffd6c234f
      - flag:
          name: enableTutorialRomain
          value: "false"
    flagValue: false
