---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: lkBool

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 49
    option: true
  - percentage: 51
    option: false

conditions: []
