---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: lkBool

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 51
    option: true
  - percentage: 49
    option: false

conditions:
  - allOf:
      - property:
          name: rox.platform
          operator: regex
          operands:
            - "89"
    flagValue: false
