---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: newbool

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 50
    option: true
  - percentage: 50
    option: false

conditions:
  - allOf:
      - property:
          name: rox.now
          operator: before
          operands:
            - "2025-03-11T22:00:00.000Z"
    flagValue: true
