---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: newbool

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 50
    option: true
  - percentage: 50
    option: false

conditions:
  - allOf:
      - flag:
          name: numberFlag
          value: "16"
    flagValue: true
