---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: numberFlag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: 4

conditions:
  - allOf:
      - anyOf:
          - group:
              name: suborg
    flagValue:
      valueWrittenInCode: true
