---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: numberFlag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: 4

conditions:
  - allOf:
      - property:
          name: string-cp
          operator: in-array
          operands:
            - "1"
    flagValue:
      valueWrittenInCode: true
