---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: numberFlag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: 4

conditions:
  - allOf:
      - property:
          name: string-cp
          operator: in-array
          operands:
            - "1"
            - x7La9KpQ
            - Zr2eN8fV
            - wTq3J5Lm
            - u9EyBd6R
            - Cm1Vx0Za
            - kQe3Wu7N
            - Hy8PbLs2
            - Tz4NwQk9
            - Mp3cYvLr
            - Je6DqXtB
            - abcd efgh
    flagValue:
      valueWrittenInCode: true
