---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: romain

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: test prop
          operator: is-false
    flagValue: false
