---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: test

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - anyOf:
          - group:
              name: test-delete
    flagValue: false
