---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: number-flag

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: testrom
          operator: in-array
          operands:
            - asdfsdf
    flagValue: 456
