---
apiVersion: v1
kind: flag-configuration

flag: aalkuz

enabled: false

defaultValue: - percentage: 0
  from: 2024-10-18T10:07:00Z
- percentage: 100
  from: 2024-10-18T10:12:00Z

conditions:
  - allOf:
      - property:
          name: rox.app_release
          operator: in-array
          operands:
              - "23"
              - "22"
    flagValue: true
