---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: corinne

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.distinct_id
          operator: regex
          operands:
            - "123"
    flagValue:
      valueWrittenInCode: true
  - allOf:
      - property:
          name: test prop
          operator: is-true
    flagValue:
      valueWrittenInCode: true
