---
apiVersion: v1
kind: flag-configuration

flag: corinne

enabled: false

defaultValue: valueWrittenInCode: true

conditions:
  - allOf:
      - anyOf:
          - group:
              name: parent
          - group:
              name: suborg
    flagValue:
      valueWrittenInCode: true
