---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: corinne

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - anyOf:
          - group:
              name: BetaUsers
          - group:
              name: BetaUsers
          - group:
              name: BetaUsers
          - group:
              name: cbp-tg1
          - group:
              name: Early Access
          - group:
              name: suborg
    flagValue:
      valueWrittenInCode: true
