---
apiVersion: v1
kind: flag-configuration

flag: corinne2

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: true

conditions:
  - allOf:
      - anyOf:
          - group:
              name: tg1
    flagValue: true
