---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: corinne

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.app_release
          operator: regex
          operands:
            - "121234"
    flagValue:
      valueWrittenInCode: true
