---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: romain

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - property:
          name: test-cp
          operator: is-true
    flagValue: false
