---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: string-flag

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: 'hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello '

conditions:
  - allOf:
      - property:
          name: rox.screen_width
          operator: is-undefined
    flagValue:
      valueWrittenInCode: true
