---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: string-flag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: 'hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello '

conditions:
  - allOf:
      - property:
          name: teststickiness1
          operator: eq
          operands:
            - 2
    flagValue:
      valueWrittenInCode: true
