---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: rom-number

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: cp-1
          operator: is-true
    flagValue: 1
  - allOf:
      - anyOf:
          - group:
              name: tg-1
    flagValue: 2
