---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: default.fontColor
flagType: string
description: ""
labels:

availableValues:
  - Red
  - Green
  - Blue
  - Black

isPermanent: false
