---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: number-flag

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 33
    option: 777
  - percentage: 33
    option: 456
  - percentage: 34
    option: 1345

conditions: []
