---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: titleSizeRomain

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - flag:
          name: number-flag
          value: "1345"
    flagValue:
      valueWrittenInCode: true
  - allOf:
      - anyOf:
          - group:
              name: gregTG
    flagValue:
      valueWrittenInCode: true
  - allOf:
      - property:
          name: string-prop
          operator: in-array
          operands:
            - hello
    flagValue: 18
